Implement config system partially
ShaharNaveh/snadra pull request #95
Opened 2021-06-02 16:15 UTC by ItayNaveh

without config file and defualts

implemented command line arguments (see TODO)
and enviorment variables

2021-06-03 13:09 UTC, ShaharNaveh commented on src/snadra/_config/__init__.py
> +    options, _ = getopt.getopt(sys.argv[1:], "", ["postgres_host=", "postgres_user="])
why not use ```argparse```?

2021-06-03 13:09 UTC, ShaharNaveh commented on src/snadra/_config/__init__.py
> +def setupConfig():
```suggestion
def setup_config():
```

We are not coding in java:)

2021-06-03 13:10 UTC, ShaharNaveh commented on src/snadra/__main__.py
> +    setupConfig()
```suggestion
    setup_config()
```

We are not coding in java:)

2021-06-03 15:08 UTC, ItayNaveh commented
should the config path be:
`~/.config/snadra.toml`
or
`~/.config/snadra/config.toml`
?

2021-06-03 15:13 UTC, ShaharNaveh commented
> should the config path be:
> `~/.config/snadra.toml`
> or
> `~/.config/snadra/config.toml`
> ?

The later. (```~/.config/snadra/config.toml```)

2021-06-05 13:02 UTC, ShaharNaveh requested changes
Overall you did implement features that we will want (one day), but for now this is an overkill.
Let's KISS, and just have one function that reads the config file, and returns a dict:)

But in general, you do have some great ideas, but for now lets KISS

2021-06-05 13:29 UTC, ItayNaveh commented
so what do i need to change?

2021-06-05 13:49 UTC, ShaharNaveh commented
> so what do i need to change?

Basically everything.
It's not that the code is not good, it's just that the code is not needed (ATM).

Write **one** function, that get the config file path as an argument, and returns a python dictionary of the parsed toml file.

2021-06-05 15:01 UTC, ShaharNaveh commented on src/snadra/_config/__init__.py
> +        config_file_data = rtoml.loads(f.read())
```suggestion
        config_file_data = rtoml.load(f)
```

2021-06-05 15:01 UTC, ShaharNaveh commented
Beside the comment this is a LGTM.

Also once the CI goes green, you can merge:)

2021-06-05 15:03 UTC, ItayNaveh commented
@ShaharNaveh fix your ci
it shouldn't complain

2021-06-06 14:51 UTC, ShaharNaveh approved these changes

2021-06-06 14:52 UTC, ShaharNaveh commented
Thanks @ItayNaveh

2021-06-06 14:52 UTC, merged